language: java
jdk:
  - openjdk11
dist: focal
git:
  depth: 3
  submodules: false
before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
script:
  - mvn test -B
cache:
  directories:
    - $HOME/.m2