name: Mtg Card Fetch Bot

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_review:
    type: [submitted]

jobs:
  fetch-card-references:
    name: Fetch MTG Card
    runs-on: ubuntu-latest
    steps:
      - uses: ldeluigi/mtg-fetch-action@v1
